<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Siswa;
use App\Models\Kelas;
use App\Models\PembayaranSpp;
use DB;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('t_pembayaran_spp')->delete();

        $siswas = [
            ["id" => 1, "name" => "ABDUL HARIS", "address" => "KP CIWAHANG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 2, "name" => "Abdul Muhamad Raihan", "address" => "Kp. Kubang, RT 1	, RW 3	Sakawayana	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 3, "name" => "Abdul rohman Saepuloh", "address" => "Sukamaju, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "082317996252", "gender" => "Laki - laki"],
            ["id" => 4, "name" => "ABDUL SALAM", "address" => "KP. LEWO WETAN, RT 	, RW 	LEWO BARU	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 5, "name" => "ACENG MUHAMAD YUSUF", "address" => "KP CICADAS, RT 	, RW 	LIMBANGAN BARAT	Kec. Blubur Limbangan	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 6, "name" => "Ade Hilmi Dikri", "address" => "Kp. Cilimus RT 01 RW 03, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "081214979320", "gender" => "Laki - laki"],
            ["id" => 7, "name" => "Ade Mulyana", "address" => "Kp. Sender, RT 3	, RW 7	Cisitu	Kec. Malangbong	44188", "phone" => "081220057377", "gender" => "Laki - laki"],
            ["id" => 8, "name" => "ADE SITI HASANAH", "address" => "KP. LEGOK 1, RT 	, RW 	MEKARASIH	Kec. Malangbong	", "phone" => "085722718074", "gender" => "Perempuan"],
            ["id" => 9, "name" => "Adi Supriadi", "address" => "Sukamanah, RT 	, RW 	Sukamanah	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 10, "name" => "Adit Ismail", "address" => "Pasir Jambu, RT 4	, RW 6	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 11, "name" => "Agus Hilman ", "address" => "Ciwalur, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "082118090790", "gender" => "Laki - laki"],
            ["id" => 12, "name" => "AGUS SUMPENA", "address" => "Kp.Cibitung, RT 4	, RW 2	Cibunar	Kec. Malangbong	44188", "phone" => "085322065555", "gender" => "Laki - laki"],
            ["id" => 13, "name" => "Ahmad Badawi Alkusumah", "address" => "Kp Cikondeh, RT 2	, RW 5	Margaluyu	Kec. Leles	44152", "phone" => "088809501690", "gender" => "Laki - laki"],
            ["id" => 14, "name" => "Ahmad Dani", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "081312283612", "gender" => "Laki - laki"],
            ["id" => 15, "name" => "AHMAD GUNAWAN", "address" => "KP CIKURAY, RT 	, RW 	MEKARSARI	Kec. Cikajang	", "phone" => "081994162013", "gender" => "Laki - laki"],
            ["id" => 16, "name" => "Ahmad Syahroni", "address" => "Kp Ciwahang, RT 1	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 17, "name" => "AI DEWI TARWIYAH", "address" => "KP CANGKUDU , RT 	, RW 	WARGAKERTA	Kec. Sukarame	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 18, "name" => "AI JUWITA", "address" => "KP. RAGAHIANG, RT 3	, RW 3	SUKAMAJU	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 19, "name" => "Ai Nuraeni", "address" => "Kp. Tajur halang, RT 2	, RW 4	Cikarag	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 20, "name" => "Ai Siti Fatimah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "089662741437", "gender" => "Perempuan"],
            ["id" => 21, "name" => "Ai Siti Munawaroh", "address" => "Kp. Cibangkerong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "085157443409", "gender" => "Perempuan"],
            ["id" => 22, "name" => "Aini Rizkiya Agustin", "address" => "Kp. Panamur, RT 3	, RW 8	Kersamanah	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 23, "name" => "AIP SOLIHIN", "address" => "KP. CIGADOG LEBAK, RT 	, RW 	SUKARASA	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 24, "name" => "AISAH NURSAPITRI", "address" => "KP. PUNCAK SARI, RT 1	, RW 6	CINAGARA	Kec. Malangbong	44188", "phone" => "085157443409", "gender" => "Perempuan"],
            ["id" => 25, "name" => "Ala Nurmala", "address" => "Kp. Muncang Agung, RT 2	, RW 8	Ds. Malangbong	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 26, "name" => "ALI SODIKIN", "address" => "DUSUN CITATAH, RT 3	, RW 5	RANGGON	Kec. Darmaraja	45372", "phone" => "088218417393", "gender" => "Laki - laki"],
            ["id" => 27, "name" => "ALIDA FATMA NURSANI", "address" => "Kp. Cijolang, RT 1	, RW 1	Cijolang	Kec. Blubur Limbangan	44186", "phone" => "085320353119", "gender" => "Perempuan"],
            ["id" => 28, "name" => "Alwi Sihabudin", "address" => "Kp.Cibunar, RT 2	, RW 4	Ds.Cibunar	Kec. Malangbong	44188", "phone" => "082164503375", "gender" => "Laki - laki"],
            ["id" => 29, "name" => "ALY ABDUL ROHMAN", "address" => "Kp Ciwahang, RT 4	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 30, "name" => "ALYA RAHMA OKTAVIRA", "address" => "Pasir Oncom, RT 1	, RW 9	Pasanggrahan	Kec. Sukawening	44184", "phone" => "085294845842", "gender" => "Perempuan"],
            ["id" => 31, "name" => "Amarani", "address" => "Karangmulya, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 32, "name" => "Aneu Nurasiah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "089656333905", "gender" => "Perempuan"],
            ["id" => 33, "name" => "Angga Abdul Rozak", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "0881023736177", "gender" => "Laki - laki"],
            ["id" => 34, "name" => "Angga Margana", "address" => "Ciwalur, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "082317224573", "gender" => "Laki - laki"],
            ["id" => 35, "name" => "Anggi Mustopa", "address" => "Kp. Cieurih RT 03 RW 03 , RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "085294470054", "gender" => "Laki - laki"],
            ["id" => 36, "name" => "Ani Kartika", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "082321741689", "gender" => "Perempuan"],
            ["id" => 37, "name" => "ARDI ANGGARA", "address" => "KP KARANG TENGAH, RT 4	, RW 2	CINAGARA	Kec. Malangbong	44188", "phone" => "085769491096", "gender" => "Laki - laki"],
            ["id" => 38, "name" => "Arif Burhanudin", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 39, "name" => "Asti Mulyani", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 40, "name" => "Astri Nurul Hidayah", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 41, "name" => "ASTRID NURLANTI", "address" => "KP. BOJONG, RT 9	, RW 1	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "085224122654", "gender" => "Perempuan"],
            ["id" => 42, "name" => "AYU FITRIYANI", "address" => "KP CIBITUNG, RT 3	, RW 2	CIBUNAR	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 43, "name" => "AYU SRI YANTI", "address" => "KP. NGONTONG, RT 	, RW 	PASANGGRAHAN	Kec. Sukawening	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 44, "name" => "Azka Hadiatul Gina", "address" => "Karoya, RT 	, RW 	Sukamerang	Kec. Kersamanah	", "phone" => "0895331968479", "gender" => "Perempuan"],
            ["id" => 45, "name" => "AZKA NAILA NAZMA MILLAH", "address" => "PASAR KOLOT, RT 1	, RW 3	MALANGBONG	Kec. Malangbong	44188", "phone" => "083116651693", "gender" => "Perempuan"],
            ["id" => 46, "name" => "Cepi Abdul Aziz", "address" => "Panamur, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 47, "name" => "Ciyntia Iswandari", "address" => "Sukamaju, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "083861849375", "gender" => "Perempuan"],
            ["id" => 48, "name" => "DAIS", "address" => "KP CILIMUS, RT 	, RW 	KARANGMULYA	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 49, "name" => "Dede Hasanah", "address" => "Pasir jambu, RT 4	, RW 6	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 50, "name" => "Dede Kosim", "address" => "Kp. Cipari, RT 1	, RW 7	Desa Simpen Kaler	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 51, "name" => "Dede Siti Rohmah", "address" => "Kp. Pasir Jambu, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 52, "name" => "DELIA ARYANI", "address" => "Kp.Kancil, RT 3	, RW 4	Girijaya	Kec. Kersamanah	44185", "phone" => "085224121812", "gender" => "Perempuan"],
            ["id" => 53, "name" => "DENI ABDULAH", "address" => "Kp. Baros Satu, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 54, "name" => "DERYN MUNAJAT", "address" => "KP. SADANG, RT 	, RW 	PADAULUN	Kec. Majalaya	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 55, "name" => "DESY AFRILLITA", "address" => "KP. SUMUR BANDUNG, RT 2	, RW 10	KARAMATMULYA	Kec. Soreang	40914", "phone" => "", "gender" => "Perempuan"],
            ["id" => 56, "name" => "Devi Astuti ", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 57, "name" => "DEVIA ANDRIANI", "address" => "KP. CIAROG, RT 4	, RW 3	Kersamanah	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 58, "name" => "Dewi Kartika", "address" => "Kp. Cisitu, RT 2	, RW 6	Cisitu	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 59, "name" => "DEWITA NUR JULIARANI", "address" => "WARUNG JAMBU, RT 	, RW 	BANTARJATI	Kec. Kota Bogor Utara	", "phone" => "08979896809", "gender" => "Perempuan"],
            ["id" => 60, "name" => "Didi", "address" => "Kp. Cieurih RT 03 RW 03 , RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 61, "name" => "DILA NURBANI SOFA", "address" => "Suka Asih, RT 2	, RW 6	Karanganyar	Kec. Kawalu	46182", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 62, "name" => "Dila Nurfadila", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 63, "name" => "Dimas Adiputra Nurdin", "address" => "Kp. Panamur, RT 	, RW 	Kersamanah	Kec. Blubur Limbangan	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 64, "name" => "DIMAS MINHAZUL FALAH", "address" => "PANAMUR, RT 4	, RW 8	Kersamanah	Kec. Kersamanah	44185", "phone" => "082164509428", "gender" => "Laki - laki"],
            ["id" => 65, "name" => "DINDA AMANDA VANIA", "address" => "Kp.Sukaresmi, RT 2	, RW 1	Cibunar	Kec. Malangbong	44188", "phone" => "083143175515", "gender" => "Perempuan"],
            ["id" => 66, "name" => "DINDA DAMAYANTI", "address" => "KP. CIKADONGDONG, RT 3	, RW 3	MEKARMULYA	Kec. Malangbong	44188", "phone" => "089691342622", "gender" => "Perempuan"],
            ["id" => 67, "name" => "DINDA RIZKIA AGNATASYA", "address" => "Cigawir, RT 3	, RW 8	Cigawir	Kec. Selaawi	44187", "phone" => "081222481760", "gender" => "Perempuan"],
            ["id" => 68, "name" => "Dinda Siti Julaeha", "address" => "Kp Cijangkar, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 69, "name" => "DINI ASTRIANIR", "address" => "ERPAH, RT 5	, RW 3	CILAMPUYANG	Kec. Malangbong	44188", "phone" => "085659099439", "gender" => "Perempuan"],
            ["id" => 70, "name" => "DINI HASBIATUL UMAH", "address" => "Sukamanah, RT 1	, RW 10	Simpen Kidul	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Perempuan"],
            ["id" => 71, "name" => "DZUROTUL AISYAH", "address" => "Kp. Selang Cau, RT 3	, RW 13	WANASARI	Kec. Cibitung	17520", "phone" => "", "gender" => "Perempuan"],
            ["id" => 72, "name" => "ELIS SITI JAMILAH", "address" => "KP CILIMUS, RT 	, RW 	KARANGMULYA	Kec. Malangbong	", "phone" => "085776994188", "gender" => "Perempuan"],
            ["id" => 73, "name" => "Eneng Helmalia Putri", "address" => "cinagara, RT 2	, RW 3	cinagara	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 74, "name" => "Ersi Rismawati", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 75, "name" => "Ervina Maharani", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "081779422445", "gender" => "Perempuan"],
            ["id" => 76, "name" => "EUIS UMIKULSUM", "address" => "KP KALIPAKSI, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "085323330271", "gender" => "Perempuan"],
            ["id" => 77, "name" => "EVA YULIANTI", "address" => "SIRNASARI, RT 4	, RW 3	MEKARASIH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 78, "name" => "Fadly Abdul Azij", "address" => "Kp. Kamasan, RT 1	, RW 6	Sukarasa	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 79, "name" => "Faojudin Akbar", "address" => "Kp. Cibangkerong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 80, "name" => "FIKRI HANIF", "address" => "Kp. Cicadas, RT 1	, RW 3	Limbangan Barat	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 81, "name" => "FINA SOPIAH", "address" => "KP. SIMPEN POJOK, RT 	, RW 	SIMPEN KALER	Kec. Blubur Limbangan	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 82, "name" => "Friska Wulandari", "address" => "Kp Pasir Baros, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 83, "name" => "Gun Gun Gunawan", "address" => "Kp. Cilimus RT 02 RW 03, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 84, "name" => "HALIDA NAZLA NUGRAHA", "address" => "Kp. Cibacang, RT 2	, RW 9	Majasari	Kec. Cibiuk	44193", "phone" => "089628912111", "gender" => "Perempuan"],
            ["id" => 85, "name" => "Halimahtussadiah", "address" => "Gg. Ikhlas Halteu Utara, RT 9	, RW 11	Dunguscariang	Kec. Andir	40183", "phone" => "083817274552", "gender" => "Perempuan"],
            ["id" => 86, "name" => "HAMIM RUSLAN", "address" => "KP CIJERUK HILIR, RT 	, RW 	SIRNASARI	Kec. Jatinunggal	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 87, "name" => "HANDAYANTI", "address" => "KP.SUNDULAN, RT 2	, RW 7	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "083869991400", "gender" => "Perempuan"],
            ["id" => 88, "name" => "HARRIS SOPIAN SAURI", "address" => "KP. SADANG, RT 	, RW 	PADAULUN	Kec. Majalaya	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 89, "name" => "HASBI ABDULLAH", "address" => "SUKAMAJU, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 90, "name" => "HERA GUSTINI DEWI", "address" => "DUSUN SUKAMULYA, RT 	, RW 	CIGENTUR	Kec. Tanjungkerta	", "phone" => "085294001626", "gender" => "Perempuan"],
            ["id" => 91, "name" => "HILWA NUZILAH", "address" => "KP. SAWAH BERA, RT 	, RW 	LIMBANGAN BARAT	Kec. Blubur Limbangan	", "phone" => "085860226500", "gender" => "Perempuan"],
            ["id" => 92, "name" => "HOERUDIN", "address" => "KP LEMBUR SAWAH, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 93, "name" => "Ihsan Muhamad Raihan", "address" => "Kp Ciwahang, RT 6	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 94, "name" => "IHWAN NUDIN", "address" => "Kp. Cicantel, RT 1	, RW 10	Girimukti	Kec. Cibatu	44185", "phone" => "085294783750", "gender" => "Laki - laki"],
            ["id" => 95, "name" => "Ila Nabila Rahmawati", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "08989122053", "gender" => "Perempuan"],
            ["id" => 96, "name" => "Ilham", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 97, "name" => "Imam Jaenal Mustofa", "address" => "Kp. Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 98, "name" => "IMANUR AJIZAH", "address" => "kp. cilimus, RT 2	, RW 3	karangmulya	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 99, "name" => "IMAS ALAWIAH", "address" => "KP SUKAMANAH, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 100, "name" => "IMAS YANTI SALAMI", "address" => "kp. pasir baros, RT 5	, RW 5	campaka	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 101, "name" => "Indah Siti Mardiah", "address" => "Kp. Cikadongdong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 102, "name" => "INTAN LATHIFATUL MAKKIYYAH", "address" => "SUMEDANG, RT 	, RW 	JATINANGOR	Kec. Paseh	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 103, "name" => "Ipal Pauji", "address" => "Kp. Cieurih RT 03 RW 03 , RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 104, "name" => "IQBAL ARDIANSYAH", "address" => "Kp. Jelegong, RT 2	, RW 16	Jelegong	Kec. Kutawaringin	", "phone" => "082116568705", "gender" => "Laki - laki"],
            ["id" => 105, "name" => "IRA HERA WATI", "address" => "KP.LEGOK 2, RT 1	, RW 7	DESA MEKARASIH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 106, "name" => "IRA MASRUROH", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 107, "name" => "Irfan Kurniawan", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 108, "name" => "IRFAN MURODI", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 109, "name" => "IRMA NURMALASARI", "address" => "KP CIGADOG WETAN, RT 	, RW 	SUKARASA	Kec. Malangbong	", "phone" => "083849637291", "gender" => "Perempuan"],
            ["id" => 110, "name" => "Irma Siti Maryam", "address" => "KP.LEGOK  2, RT 4	, RW 7	MEKARASIH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 111, "name" => "IRNA NURMALA", "address" => "KP. WARUDOYONG, RT 2	, RW 3	CIHAURKUNING	Kec. Malangbong	44188", "phone" => "082120104682", "gender" => "Perempuan"],
            ["id" => 112, "name" => "Irpan Tajil Mutakin", "address" => "Ciwalur, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 113, "name" => "Iyang Hidayat", "address" => "Kp. Sender, RT 4	, RW 7	Cisitu	Kec. Malangbong	44188", "phone" => "083877450869", "gender" => "Laki - laki"],
            ["id" => 114, "name" => "Jihan Yulianti", "address" => "Karangmulya, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 115, "name" => "JUJUN JUNAEDI", "address" => "KP. RAGAHIANG, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 116, "name" => "JULIA FITRI YANINGSIH", "address" => "KP. BATU NANJEUR, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 117, "name" => "KAMIL SYEHABUDIN", "address" => "CIKONDANG, RT 2	, RW 2	GIRIJAYA	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 118, "name" => "Karina Delia", "address" => "Limbangan, RT 	, RW 	Bl Limbangan	Kec. Blubur Limbangan	", "phone" => "081905423909", "gender" => "Perempuan"],
            ["id" => 119, "name" => "KARMILA", "address" => "Sukamanah, RT 3	, RW 11	Simpen Kidul	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Perempuan"],
            ["id" => 120, "name" => "Kartiwan", "address" => "Ciwalur, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 121, "name" => "LADUNI RIZKI SAJIDA", "address" => "KP. CIBITUNG KULON, RT 	, RW 	CIBUNAR	Kec. Malangbong	", "phone" => "089699527773", "gender" => "Laki - laki"],
            ["id" => 122, "name" => "LELA NURLELASARI", "address" => "KP PANGKALAN, RT 	, RW 	CISITU	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 123, "name" => "Lilis Atikah", "address" => "Babakan jaya mulya, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 124, "name" => "Lilis Pitriani ", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 125, "name" => "Lisnawati", "address" => "Kp Babakan Taman, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 126, "name" => "LISTI FADILAH NUR AZIZAH", "address" => "KP. CIGADOG, RT 0	, RW 0	SUKARASA	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 127, "name" => "LULU NAFISAH QUROTU AENI", "address" => "KP. SURIAN, RT 4	, RW 2	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "082315122762", "gender" => "Perempuan"],
            ["id" => 128, "name" => "M Fikri Firdaus", "address" => "Kp Ciwahang, RT 7	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 129, "name" => "M. Ardiansyah", "address" => "Kp. Cikadu, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "083844462055", "gender" => "Laki - laki"],
            ["id" => 130, "name" => "M. FIQRI FAHRUROZI", "address" => "KP. CIORAY HILIR, RT 2	, RW 11	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "085224121281", "gender" => "Laki - laki"],
            ["id" => 131, "name" => "M. Irpan", "address" => "Kp. Muncang Agung, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 132, "name" => "M. Kahfi Asshouqi", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 133, "name" => "M. SALMAN PARIS", "address" => "Kp. Muncang Agung, RT 2	, RW 8	Ds. Malangbong	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 134, "name" => "M. Taupik S", "address" => "Kp. Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 135, "name" => "Marsela Fauziah", "address" => "Kp. Leuweung Kaleng, RT 4	, RW 2	Katapang	Kec. Katapang	40971", "phone" => "089662193104", "gender" => "Perempuan"],
            ["id" => 136, "name" => "Maulida Ainun Najibah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 137, "name" => "MAULIDIYA SARI", "address" => "Kp Cioray, RT 3	, RW 9	Nanjungjaya	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 138, "name" => "MELA SITI RUKOYAH", "address" => "Kp. Salapinang, RT 2	, RW 6	Campaka	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 139, "name" => "MELANI DYANTI", "address" => "SUKAMAJU, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 140, "name" => "Melia Rahayu", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 141, "name" => "MEMEY MAEMUNAH", "address" => "KP.CIKADU, RT 3	, RW 5	CAMPAKA	Kec. Malangbong	44188", "phone" => "085213006227", "gender" => "Perempuan"],
            ["id" => 142, "name" => "MIFTAH NURDIN RAMDANI", "address" => "KP BABAKAN SUKAJADI, RT 	, RW 	TANJUNGLAYA	Kec. Cikancung	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 143, "name" => "Mila Siti Armilah", "address" => "KP.LEGOK 2, RT 2	, RW 7	MEKARASIH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 144, "name" => "MITA KHOERUNISA", "address" => "Sukamulya, RT 2	, RW 9	Pasanggrahan	Kec. Sukawening	44184", "phone" => "085721613256", "gender" => "Perempuan"],
            ["id" => 145, "name" => "MOCHAMAD NURZIAD", "address" => "KP. MIJI, RT 	, RW 	TANJUNGLAYA	Kec. Cikancung	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 146, "name" => "MUH. RAMDANI", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 147, "name" => "MUH. RIFKI MAULANA", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 148, "name" => "MUHAMAD AAS NASYRUDIN", "address" => "KP. CIJANGKAR, RT 1	, RW 9	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 149, "name" => "Muhamad Ali Purnama", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 150, "name" => "MUHAMAD ALWI ASYA'RONI", "address" => "KP CIHALIWUNG, RT 1	, RW 19	CILEUNYI KULON	Kec. Cileunyi	40621", "phone" => "082164509477", "gender" => "Laki - laki"],
            ["id" => 151, "name" => "Muhamad Fabi Nasruloh", "address" => "Panamur, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 152, "name" => "MUHAMAD FATHIR ALFARIZQI", "address" => "Nagreg, RT 8	, RW 20	Nagreg	Kec. Nagreg	40397", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 153, "name" => "Muhamad Mustopa Kamal", "address" => "Kp. Cisitu, RT 3	, RW 5	Cisitu	Kec. Malangbong	44188", "phone" => "083890061867", "gender" => "Laki - laki"],
            ["id" => 154, "name" => "MUHAMAD NIZAR", "address" => "Kp. Panamur, RT 3	, RW 8	Kersamanah	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 155, "name" => "MUHAMAD RAYHAN", "address" => "Kp. Saunggunung, RT 3	, RW 6	Cibunar	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 156, "name" => "Muhamad Tajul Aripin", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 157, "name" => "MUHAMAD TONI SETIAWAN", "address" => "KP CIBITUNG, RT 3	, RW 2	CIBUNAR	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 158, "name" => "MUHAMAD WILDAN FAUZI", "address" => "Kp. Cisitu Kidul, RT 3	, RW 6	cisitu	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 159, "name" => "MUHAMAD ZENAL ARIPIN", "address" => "Kp. Cieunteung, RT 4	, RW 3	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 160, "name" => "Muhammad Abdul Halim", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 161, "name" => "MUHAMMAD ADITIA RIFALDI", "address" => "KP. BOJONG, RT 3	, RW 11	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "085224121298", "gender" => "Laki - laki"],
            ["id" => 162, "name" => "Muhammad Alan", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 163, "name" => "MUHAMMAD FADLI", "address" => "KP. PASAR SORE, RT 3	, RW 5	CILEUNYI WETAN	Kec. Cileunyi	40622", "phone" => "082164509496", "gender" => "Laki - laki"],
            ["id" => 164, "name" => "Muhammad Ramdan H", "address" => "Kp. Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 165, "name" => "Muhammad Ridwan Aunillah", "address" => "Kp.Dunguswiru, RT 1	, RW 4	Dunguswiru	Kec. Blubur Limbangan	44186", "phone" => "08977325902", "gender" => "Laki - laki"],
            ["id" => 166, "name" => "MUHAMMAD SAEPUL JAMIL", "address" => "KP. SINDANGHEULA, RT 3	, RW 2	SUKAMAJU	Kec. Kersamanah	44185", "phone" => "082164509498", "gender" => "Laki - laki"],
            ["id" => 167, "name" => "Muhammad Syaripudin", "address" => "KP. SINDANGSARI, RT 3	, RW 11	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 168, "name" => "MUSTOFA RAMDANI", "address" => "Kp. Cimuncang, RT 4	, RW 1	Mekarmulya	Kec. Malangbong	44188", "phone" => "083160757740", "gender" => "Laki - laki"],
            ["id" => 169, "name" => "NAILA HISNI AZZAHRA", "address" => "KP. CIGADOG, RT 3	, RW 3	SUKARASA	Kec. Malangbong	44188", "phone" => "085224122158", "gender" => "Perempuan"],
            ["id" => 170, "name" => "Naila Patimah", "address" => "Kp. Buah Condong, RT 1	, RW 3	Mekarwangi	Kec. Sukawening	44184", "phone" => "082164509452", "gender" => "Perempuan"],
            ["id" => 171, "name" => "NASYWA SHABILA MAOLIDAH", "address" => "Kp. Cicadas, RT 2	, RW 3	Limbangan Barat	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Perempuan"],
            ["id" => 172, "name" => "NAUFAL ANANDA PUTRA", "address" => "KP. LEMBUR SAWAH, RT 1	, RW 3	SUKAMAJU	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 173, "name" => "Nayla Lasiamal Aulia", "address" => "Kp Reuma, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 174, "name" => "NAZWA QORRY KHOIRUNNISA", "address" => "KP. SURIAN, RT 4	, RW 2	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "085224121943", "gender" => "Perempuan"],
            ["id" => 175, "name" => "Nenden Ayu Laswati", "address" => "Kp. Cilimus RT 01 RW 03, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 176, "name" => "NENDEN RIDA SITI ROSYIDAH", "address" => "Karang Asih, RT 2	, RW 5	Sukajadi	Kec. Wado	45373", "phone" => "", "gender" => "Perempuan"],
            ["id" => 177, "name" => "NENDEN SITI NURHASANAH", "address" => "KP CILIMUS, RT 	, RW 	KARANGMULYA	Kec. Malangbong	", "phone" => "085871034363", "gender" => "Perempuan"],
            ["id" => 178, "name" => "NENG SUCI ANUGAH", "address" => "KP CIWAHANG, RT 4	, RW 5	SUKAMANAH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 179, "name" => "Nita", "address" => "Kp. Suragobang RT 04 RW 04, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 180, "name" => "NOPI INDRIANI", "address" => "KP. KANCIL, RT 	, RW 	GIRIJAYA	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 181, "name" => "Nova Vitriani", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 182, "name" => "NOVI PUSPITA", "address" => "KP. WALURAN, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 183, "name" => "Noviyanti Solihah", "address" => "Ciwahang, RT 	, RW 	Sukamanah	Kec. Malangbong	", "phone" => "089671120349", "gender" => "Perempuan"],
            ["id" => 184, "name" => "Nurazizah", "address" => "Dusun Sinoman, RT 2	, RW 7	Ganjaresik	Kec. Wado	45373", "phone" => "08889431479", "gender" => "Perempuan"],
            ["id" => 185, "name" => "Nurdiansyah", "address" => "Panamur, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 186, "name" => "Nurhasanah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 187, "name" => "NURHIDAYATI", "address" => "KP BOJONG KONDANG, RT 	, RW 	CINAGARA	Kec. Malangbong	", "phone" => "08997712455", "gender" => "Laki - laki"],
            ["id" => 188, "name" => "Nuril Istyaqul Hak", "address" => "Kp. Cicadas , RT 2	, RW 8	Pasirwaru	Kec. Blubur Limbangan	44186", "phone" => "083150070561", "gender" => "Perempuan"],
            ["id" => 189, "name" => "Nurman Sulaeman", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 190, "name" => "Opi Sopiah", "address" => "Cibangkerong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 191, "name" => "PAHMI", "address" => "KP CISITU KIDUL, RT 3	, RW 6	CISITU	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 192, "name" => "PAJAR ABDUL KARIM", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 193, "name" => "Pani Handayani", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 194, "name" => "Parida", "address" => "Kp. Cibangkerong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 195, "name" => "Pina Anggraeni", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 196, "name" => "Pitriani", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 197, "name" => "PUTRI AULIA", "address" => "Kp. Muncang Agung, RT 2	, RW 8	Ds. Malangbong	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 198, "name" => "PUTRI SITI SAADAH", "address" => "KP. KANCIL, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 199, "name" => "RAGIL SIFA SULISTIONO", "address" => "JL. GALUMPIT, RT 3	, RW 23	CILEUNYI KULON	Kec. Cileunyi	40393", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 200, "name" => "RAHMA AZIZA FADILAH", "address" => "KP. PANAMUR, RT 4	, RW 8	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "085224121673", "gender" => "Perempuan"],
            ["id" => 201, "name" => "RAHMA PERTIWI", "address" => "KP CIPEUJEUH, RT 	, RW 	CAMPAKA	Kec. Malangbong	", "phone" => "083825370882", "gender" => "Perempuan"],
            ["id" => 202, "name" => "RAHMAWATI", "address" => "KP. BEBEDAHAN, RT 	, RW 	MALANGBONG	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 203, "name" => "RAMDAN  FATIHAH", "address" => "Kp Cioray, RT 1	, RW 9	Nanjungjaya	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 204, "name" => "Rangga", "address" => "Kp. Rawa Lumpang Rt. 002/013, RT 	, RW 	Salembaran Jati	Kec. Kosambi	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 205, "name" => "Rasyid Ammar", "address" => "Dusun Cimedang, RT 	, RW 	Cilengkrang	Kec. Wado	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 206, "name" => "RATNA SARI", "address" => "Kp. Muncang Agung, RT 3	, RW 8	Ds. Malangbong	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 207, "name" => "Reni Andriani", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 208, "name" => "RESTU ATOILLAH IMADUDIN", "address" => "Cioray, RT 2	, RW 9	Nanjungjaya	Kec. Kersamanah	44185", "phone" => "085224122384", "gender" => "Laki - laki"],
            ["id" => 209, "name" => "RIDHO NOVIANDI", "address" => "KP.KAMASAN, RT 1	, RW 6	SUKARASA	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 210, "name" => "Rifa Zakiyah Sayyidatul Munawaroh", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "083827879608", "gender" => "Perempuan"],
            ["id" => 211, "name" => "Rima Siti Halimatul Rip'ah", "address" => "Sukamaju, RT 3	, RW 3	Ganjaresik	Kec. Wado	45373", "phone" => "", "gender" => "Perempuan"],
            ["id" => 212, "name" => "RINA APRILIA", "address" => "Kp. Muncang Agung, RT 4	, RW 8	Ds. Malangbong	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 213, "name" => "RINA FEBRIANTI", "address" => "KP. SUKAMANAH, RT 3	, RW 2	SUKAMANAH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 214, "name" => "Rina Zakiyah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "085223668660", "gender" => "Perempuan"],
            ["id" => 215, "name" => "Rinjani", "address" => "KP.SUKABATU, RT 1	, RW 1	SANDING	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 216, "name" => "RIRIN HERLINA", "address" => "Kp. Cigalumpit, RT 1	, RW 4	Karangmulya	Kec. Malangbong	44188", "phone" => "081221000720", "gender" => "Perempuan"],
            ["id" => 217, "name" => "RISA SA'ADAH", "address" => "KP. SURIAN, RT 4	, RW 2	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 218, "name" => "RISMA NURUL FITRIYAH", "address" => "Kp. Cisitu, RT 2	, RW 6	Cisitu	Kec. Malangbong	44188", "phone" => "085780554124", "gender" => "Perempuan"],
            ["id" => 219, "name" => "RISNA MUTIA", "address" => "Cieurih, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 220, "name" => "Riyan ", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 221, "name" => "RIZKI ABDUL ROHMAN", "address" => "Kp. Babakan Loa, RT 2	, RW 3	Padalarang	Kec. Padalarang	40553", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 222, "name" => "RIZKY HASBI ASIDIK", "address" => "KP. KURNIA, RT 1	, RW 1	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "082164509434", "gender" => "Laki - laki"],
            ["id" => 223, "name" => "Ropiq Hapidmuslim", "address" => "Kp. Panamur, RT 4	, RW 8	Kersamanah	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 224, "name" => "Saep", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 225, "name" => "Saepul Malik", "address" => "Batutumpeng, RT 3	, RW 4	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 226, "name" => "SALMA SITI NUR SAADAH", "address" => "Kp. Babakan Serang, RT 1	, RW 10	Cibiuk Kaler	Kec. Cibiuk	44193", "phone" => "082321516280", "gender" => "Perempuan"],
            ["id" => 227, "name" => "Salman Alparisi", "address" => "Kp. Cioray Tengah, RT 3	, RW 8	Nanjungjaya	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 228, "name" => "Salwa Auliya Fauziyah", "address" => "Kp. Cijaringao, RT 1	, RW 2	Sukajaya	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 229, "name" => "Sandi", "address" => "Kp Ciwahang, RT 	, RW 	Sukamanah	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 230, "name" => "Sandi Abdul Rozak", "address" => "Kp. Sadang, RT 1	, RW 8	Padaulun	Kec. Majalaya	40382", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 231, "name" => "SENDY FIRMANSYAH", "address" => "KP. BABAKAN, RT 5	, RW 10	SUKATANI	Kec. Tapos	16454", "phone" => "08179808574", "gender" => "Laki - laki"],
            ["id" => 232, "name" => "SENI FAUZIAH FITRIANI", "address" => "PANAMUR, RT 	, RW 	KERSAMANAH	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 233, "name" => "SIFA NURSA'ADAH", "address" => "Cigembor, RT 2	, RW 4	MAJASARI	Kec. Cibiuk	44193", "phone" => "", "gender" => "Perempuan"],
            ["id" => 234, "name" => "Silma Aulia", "address" => "KP. KURNIA, RT 1	, RW 1	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 235, "name" => "SILPI SOPIANTI", "address" => "KP. CIJANGKAR, RT 	, RW 	KERSAMANAH	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 236, "name" => "Silva Sari", "address" => "Kp. Cibangkrong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 237, "name" => "Sindi Sopiah", "address" => "Kp Ciwahang, RT 3	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 238, "name" => "SINTA", "address" => "Cieurih, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 239, "name" => "SINTA RAMADANI", "address" => "Cieurih, RT 	, RW 	Karangmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 240, "name" => "Sipa Hoerunisa", "address" => "Sukajaya, RT 2	, RW 5	Ganjaresik	Kec. Wado	45373", "phone" => "", "gender" => "Perempuan"],
            ["id" => 241, "name" => "Siti Jubaedah", "address" => "Kp Ciwahang, RT 5	, RW 7	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 242, "name" => "SITI KARTINI", "address" => "KP CIBITUNG, RT 4	, RW 2	CIBUNAR	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 243, "name" => "Siti Maesaroh", "address" => "Kp. Pasir Jambu, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 244, "name" => "SITI MAESAROH", "address" => "KP BOJONG GENGGONG, RT 	, RW 	CILULUK	Kec. Cikancung	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 245, "name" => "SITI MUDRIKAH", "address" => "KP BEBEDAHAN, RT 	, RW 	MALANGBONG	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 246, "name" => "Siti Nabila ", "address" => "Sukamaju, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "083173354150", "gender" => "Perempuan"],
            ["id" => 247, "name" => "SITI NUR AISAH", "address" => "kp. leuwueng kaleng, RT 3	, RW 4	katapang	Kec. Katapang	40971", "phone" => "082119319818", "gender" => "Perempuan"],
            ["id" => 248, "name" => "SITI NUR AJIJAH", "address" => "KP PASIR JAMBU, RT 	, RW 	CAMPAKA	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 249, "name" => "SITI NURANISA", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 250, "name" => "SITI NURHALIMAH", "address" => "KP. WALURAN, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 251, "name" => "Siti Nurhalizah", "address" => "Kp. Cisitu, RT 2	, RW 6	Cisitu	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 252, "name" => "Siti Nurhamidah", "address" => "Kp.Cibitung, RT 1	, RW 5	Simpen Kidul	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 253, "name" => "Siti Nurjanah", "address" => "Karang Asih, RT 2	, RW 5	Sukajadi	Kec. Wado	45373", "phone" => "082129435320", "gender" => "Laki - laki"],
            ["id" => 254, "name" => "Siti Nurmala Sari", "address" => "Panamur, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "08382824789", "gender" => "Perempuan"],
            ["id" => 255, "name" => "SITI NURSOLIHAH", "address" => "Kp. Simpen, RT 1	, RW 17	Simpen Kidul	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Perempuan"],
            ["id" => 256, "name" => "SITI NURZAKIAH", "address" => "KP. LEBAK HUNI, RT 	, RW 	SUKALILAH	Kec. Cibatu	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 257, "name" => "Siti Patimah", "address" => "Kp. Citeras, RT 4	, RW 2	Bunisari	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 258, "name" => "Siti Rohimah", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 259, "name" => "SITI RUKOYAH", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 260, "name" => "SITI SALWA FITRIANTI", "address" => "KP.CICADAS, RT 2	, RW 3	LIMBANGAN BARAT	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Perempuan"],
            ["id" => 261, "name" => "Siti Sopiah", "address" => "Citamiang, RT 1	, RW 3	Pasirwaru	Kec. Blubur Limbangan	44186", "phone" => "083829720486", "gender" => "Perempuan"],
            ["id" => 262, "name" => "SITI SOPIAH", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 263, "name" => "SOFA MASPUPAH", "address" => "cigembor, RT 2	, RW 4	MAJASARI	Kec. Cibiuk	44193", "phone" => "0895805109645", "gender" => "Perempuan"],
            ["id" => 264, "name" => "Soni", "address" => "Kp. Cisitu Kidul, RT 2	, RW 6	Cisitu	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 265, "name" => "SONI SAPRULLOH", "address" => "Kp.Cibitung Kulon, RT 0	, RW 0	Cibunar	Kec. Malangbong	44188", "phone" => "089619716246", "gender" => "Laki - laki"],
            ["id" => 266, "name" => "Sri Asti", "address" => "Kp. Cibangkerong, RT 	, RW 	Mekarmulya	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 267, "name" => "Sri Fitriyani", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 268, "name" => "Sri Mulyani", "address" => "Baros, RT 	, RW 	Sukamaju	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 269, "name" => "Sri Wahyuni", "address" => "Ciwahang, RT 	, RW 	Sukamanah	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 270, "name" => "Susan", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 271, "name" => "Susan Ayu Lestari", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 272, "name" => "SUSILAWATI", "address" => "KP. PANAMUR, RT 	, RW 	KERSAMANAH	Kec. Kersamanah	", "phone" => "085219875398", "gender" => "Perempuan"],
            ["id" => 273, "name" => "SYARIEF HIDAYATULLOH", "address" => "KP. PESANTREN TENGAH, RT 1	, RW 2	CIBIUK KIDUL	Kec. Cibiuk	44193", "phone" => "082164509450", "gender" => "Laki - laki"],
            ["id" => 274, "name" => "SYIFA KHOIRIYYAH", "address" => "Jln stasiun timur Gg arumanis, RT 4	, RW 3	Kebonjati	Kec. Cikole	43122", "phone" => "085871571938", "gender" => "Perempuan"],
            ["id" => 275, "name" => "TIA DIANTI", "address" => "KP.LEGOK 2, RT 3	, RW 7	MEKARASIH	Kec. Malangbong	44188", "phone" => "", "gender" => "Perempuan"],
            ["id" => 276, "name" => "TIARA NURLIDIANA", "address" => "Kp. Kurnia, RT 5	, RW 1	Kersamanah	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 277, "name" => "TIKA SITI MUDRIKAH", "address" => "KP SUKAMANAH, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 278, "name" => "TONI M SIDIK", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 279, "name" => "Triguna Darojat ", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 280, "name" => "Tsabita  Faridatul Ula", "address" => "Kp Palalangon, RT 5	, RW 6	Nanjungjaya	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 281, "name" => "Usep Akmal", "address" => "KP. CIJANGKAR, RT 3	, RW 10	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 282, "name" => "Usman Sapta Hadi", "address" => "Kp Ciwahang, RT 7	, RW 5	Sukamanah	Kec. Malangbong	44188", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 283, "name" => "VIVI CAHYA AFRILIA", "address" => "KP. BINUANG, RT 4	, RW 11	KERSAMANAH	Kec. Kersamanah	44185", "phone" => "", "gender" => "Perempuan"],
            ["id" => 284, "name" => "WANDA HAMIDAH", "address" => "KP. KANCIL, RT 	, RW 	SUKAMAJU	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 285, "name" => "WIDIA NINGSIH", "address" => "KP. KERED, RT 	, RW 	NANJUNGJAYA	Kec. Kersamanah	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 286, "name" => "Widya Wulandari", "address" => "Kp. Lemburkuring, RT 3	, RW 9	Pasanggrahan	Kec. Sukawening	44184", "phone" => "081461228079", "gender" => "Perempuan"],
            ["id" => 287, "name" => "Wildan Muhammad Zaky", "address" => "Kp. Panamur, RT 	, RW 	Kersamanah	Kec. Blubur Limbangan	", "phone" => "082164509504", "gender" => "Laki - laki"],
            ["id" => 288, "name" => "WIRIYA", "address" => "KP. SIMPEN, RT 1	, RW 6	SIMPEN KALER	Kec. Blubur Limbangan	44186", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 289, "name" => "WISNU GINANJAR ", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 290, "name" => "Wiwin Widia Nengsih", "address" => "Kp. Tugumukti, RT 3	, RW 4	Tugu Mukti	Kec. Cisarua	40551", "phone" => "", "gender" => "Perempuan"],
            ["id" => 291, "name" => "WULAN FANI NURAENI", "address" => "Kp.Kancil, RT 1	, RW 4	Girijaya	Kec. Kersamanah	44185", "phone" => "082164509505", "gender" => "Perempuan"],
            ["id" => 292, "name" => "Wulan Masruroh", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 293, "name" => "Yuli Sahliah", "address" => "Sinoman, RT 1	, RW 7	Ganjaresik	Kec. Wado	45373", "phone" => "", "gender" => "Perempuan"],
            ["id" => 294, "name" => "YUNI", "address" => "KP BATUTUMPENG, RT 	, RW 	SUKAMANAH	Kec. Malangbong	", "phone" => "", "gender" => "Perempuan"],
            ["id" => 295, "name" => "Yunisa Salsabila", "address" => "Ciwahang, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "085323932170", "gender" => "Perempuan"],
            ["id" => 296, "name" => "Yusup", "address" => "Kp. Bogor, RT 2	, RW 2	Sukamaju	Kec. Kersamanah	44185", "phone" => "082164509449", "gender" => "Laki - laki"],
            ["id" => 297, "name" => "YUSUP", "address" => "KP. KANCIL, RT 	, RW 	GIRIJAYA	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 298, "name" => "Yusup Firmansyah", "address" => "Panamur, RT 	, RW 	Kersamanah	Kec. Kersamanah	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 299, "name" => "Zaenal Mustofa Kamal", "address" => "Bebedahan, RT 	, RW 	Malangbong	Kec. Malangbong	", "phone" => "", "gender" => "Laki - laki"],
            ["id" => 300, "name" => "Zulfa Mardiyatillah", "address" => "Kp. Salapinang RT 03/ RW 06, RT 	, RW 	Campaka	Kec. Malangbong	", "phone" => "083896514482", "gender" => "Perempuan"],
            ["id" => 301, "name" => "Zulfah Hindriyani", "address" => "burujul, RT 	, RW 	Limbangan Barat	Kec. Blubur Limbangan	", "phone" => "", "gender" => "Perempuan"],

        ];

        $nisns = [
            "3034657790",
            "0041702637",
            "0041325159",
            "3036310672",
            "0041423154",
            "3044620887",
            "0052216741",
            "3036973322",
            "0052914423",
            "0048557213",
            "3027584181",
            "0021249810",
            "0058584838",
            "0057648073",
            "0010052426",
            "0057021177",
            "9991551692",
            "0037799564",
            "0020342331",
            "3015570539",
            "3033035003",
            "0048828783",
            "3044460933",
            "0046853786",
            "0038022259",
            "0043676507",
            "0041625726",
            "0072656306",
            "0051949635",
            "0065708819",
            "0023743477",
            "3029808914",
            "3039438936",
            "3053553430",
            "3048387723",
            "0057409506",
            "0004705137",
            "0054554590",
            "0052686463",
            "3026784092",
            "0053941702",
            "0044640649",
            "3046470880",
            "0052919580",
            "0051835623",
            "0045536236",
            "3057515752",
            "0048786541",
            "0067240541",
            "0037397268",
            "3050845910",
            "0069733895",
            "3041404517",
            "0059410620",
            "0031263512",
            "3031255178",
            "0045235779",
            "0037595256",
            "0040895663",
            "3037997550",
            "0058233714",
            "0043705268",
            "3061241150",
            "0052787656",
            "0043992237",
            "0021327468",
            "0046914871",
            "0044049715",
            "0043959378",
            "0043734006",
            "0047559685",
            "0031061153",
            "0039241105",
            "0048487490",
            "3045016051",
            "0036950617",
            "0066683997",
            "0048130110",
            "3009211883",
            "0034587912",
            "3044373819",
            "0049923225",
            "3049908149",
            "0038686145",
            "0064632600",
            "0043619045",
            "0037690603",
            "0049852561",
            "0037698557",
            "0043594391",
            "0038587968",
            "0051740336",
            "0043407430",
            "0052440491",
            "3051401248",
            "0041528114",
            "0039955488",
            "0055834710",
            "0046026632",
            "0006607490",
            "0046851088",
            "0037093386",
            "3033667569",
            "9990011698",
            "0043959205",
            "3045116307",
            "0043028746",
            "0055995933",
            "0037335949",
            "0043959207",
            "0020341495",
            "3057187832",
            "0020306428",
            "3036621971",
            "0037698552",
            "0046111472",
            "0037796044",
            "0047451354",
            "0043734001",
            "0038644529",
            "0020326204",
            "0020325953",
            "0054887803",
            "3024210578",
            "3060402843",
            "0043671684",
            "0045656020",
            "0037596117",
            "0047882684",
            "0067286286",
            "3064302685",
            "0051073733",
            "0043958166",
            "3069799896",
            "0067590286",
            "0052550473",
            "0037537995",
            "0043489564",
            "0044098335",
            "0054254960",
            "0034009088",
            "0048264797",
            "0037631473",
            "0047525770",
            "0039754379",
            "3037536699",
            "0043990447",
            "0048121603",
            "3031233917",
            "0058909072",
            "0045294741",
            "0053378262",
            "0059201135",
            "0039865986",
            "0036848759",
            "3053483073",
            "0044714716",
            "0027045458",
            "0039209176",
            "0052576931",
            "0059401453",
            "0020341281",
            "0067006364",
            "0055945845",
            "0045560227",
            "0053517256",
            "0037676001",
            "0064577808",
            "0051416754",
            "0045295615",
            "0057555279",
            "0046016284",
            "3054037346",
            "0059965850",
            "3035922763",
            "0057414200",
            "0044592682",
            "0044632740",
            "3041504647",
            "0044058688",
            "3030544205",
            "0048059873",
            "3049091884",
            "0067453502",
            "0045536238",
            "3024708802",
            "0022046320",
            "0057797672",
            "0048515447",
            "0013084920",
            "0020306403",
            "0043990444",
            "3044492394",
            "0045944917",
            "3041235131",
            "0041144130",
            "0062039315",
            "0048904283",
            "0049643235",
            "0056119447",
            "0035107710",
            "3037617180",
            "0033383646",
            "0058431490",
            "3063423009",
            "0043958175",
            "0049594269",
            "0055747163",
            "0031209416",
            "0042227187",
            "0037351089",
            "0063710554",
            "0054252524",
            "0029463181",
            "0043991461",
            "0041905743",
            "0068937104",
            "0071170383",
            "0059991125",
            "3024791131",
            "0043466129",
            "0069284614",
            "0043330802",
            "0021072856",
            "0062381462",
            "0037577341",
            "0047372285",
            "0064295785",
            "0058296571",
            "0051689062",
            "0042011274",
            "0035382895",
            "0037634100",
            "0041720943",
            "0037335939",
            "0016464458",
            "0037596126",
            "3051894134",
            "3079697910",
            "0043676637",
            "0048830859",
            "0055085760",
            "3053519780",
            "0044290969",
            "0023256298",
            "0054128024",
            "0035328139",
            "0038721488",
            "3034640076",
            "0034940483",
            "0037595244",
            "0052761262",
            "0037350199",
            "0053570085",
            "0037394928",
            "0043857686",
            "0045734343",
            "3025995721",
            "3036820944",
            "0062464630",
            "0007695060",
            "3044622218",
            "0055452363",
            "0049823180",
            "0048242323",
            "0042929899",
            "0043441682",
            "3068736509",
            "3032398216",
            "3055453633",
            "3045732220",
            "0049294083",
            "0058555179",
            "0052421462",
            "0043959219",
            "0052072490",
            "0045917680",
            "0037653932",
            "3029504866",
            "0043876213",
            "0051877991",
            "0044657896",
            "0068246278",
            "0044058679",
            "0044009645",
            "0054436925",
            "3053465753",
            "0051181716",
            "3019297380",
            "0069191698",
            "0057342820",
            "0047979003",
            "0043635191",
            "0055474402",
            "3046231766",
            "0061612983",
            "0020388773",
            "0056682575",
            "0049686978",
            "0086538092",
            "0071750489",

        ];

        $kelas = Kelas::get();

        $years = [
            'ganjil' => ['Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'],
            'genap' => ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni']
        ];

        $index = 0;
        foreach ($siswas as $siswa) {
            if (fmod($index, 3) == 0) {
                $angkatan = 1;
            } else if (fmod($index, 3)  == 1) {
                $angkatan = 2;
            } else {
                $angkatan = 3;
            }
            if (fmod($index, 2) == 0) {
                $jurusan = 1;
            } else {
                $jurusan = 2;
            }
            Siswa::updateOrCreate(
                ['id' => $siswa['id']],
                [
                    'name' => $siswa['name'],
                    'address' => $siswa['address'],
                    'phone' => $siswa['phone'],
                    'gender' => $siswa['gender'],
                    'angkatan_id' => $angkatan,
                    'jurusan_id' => $jurusan,
                    'nipd' => $nisns[$index],
                    'nisn' => $nisns[$index]
                ]
            );
            foreach ($kelas as $key) {

                for ($i=0; $i < sizeOf($years['ganjil']); $i++) {

                    PembayaranSpp::create([
                        'siswa_id' => $siswa['id'],
                        'kelas_id' => $key->id,
                        'bulan' => $years['ganjil'][$i],
                        'semester' => 'ganjil',
                        'total_payment' => '0'
                    ]);

                }

                for ($i=0; $i < sizeOf($years['genap']); $i++) {

                    PembayaranSpp::create(['siswa_id' => $siswa['id'],
                        'kelas_id' => $key->id,
                        'bulan' => $years['genap'][$i],
                        'semester' => 'genap',
                        'total_payment' => '0'
                    ]);

                }

            }
            $index++;
        }
    }
}
